import{chromium,devices}from'playwright';
const url='http://127.0.0.1:3001',errors=[];const browser=await chromium.launch({headless:true});
async function wire(page){page.on('console',m=>{if(m.type()==='error')errors.push('console: '+m.text())});page.on('pageerror',e=>errors.push('page: '+e.message));}
const page=await browser.newPage({viewport:{width:1280,height:800}});await wire(page);await page.goto(url,{waitUntil:'networkidle'});await page.getByRole('heading',{name:/NEON/}).waitFor();
await page.getByRole('button',{name:/LEADERBOARD/}).click();await page.getByText('CURRENT DIVISION').waitFor();await page.getByRole('button',{name:/MAIN MENU/}).click();
await page.getByRole('button',{name:/PROFILE/}).click();await page.getByText('PLAYER PROFILE').waitFor();await page.getByRole('button',{name:/MAIN MENU/}).click();
await page.getByRole('button',{name:/SETTINGS/}).click();await page.getByText('GRAPHICS QUALITY').waitFor();await page.getByRole('button',{name:'HIGH'}).click();await page.getByRole('slider',{name:'Master volume'}).fill('42');let volume=await page.evaluate(()=>JSON.parse(localStorage.getItem('neon-settings')||'{}').volume);if(volume!==42)errors.push('volume did not persist');let saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('neon-settings')||'{}').quality);if(saved!=='high')errors.push('settings did not persist');await page.getByRole('button',{name:/MAIN MENU/}).click();
await page.getByRole('button',{name:/HOW TO PLAY/}).click();await page.getByText('AIM & ATTACK').waitFor();await page.getByRole('button',{name:/ENTER THE ARENA/}).click();await page.getByText('SELECT BATTLEFIELD').waitFor();if(await page.locator('.map-card-play:not(:disabled)').count()!==3)errors.push('unlocked map play buttons missing');await page.getByRole('button',{name:/PLAY THIS MAP/}).click();await page.getByText('SELECT AI PROTOCOL').waitFor();await page.getByRole('button',{name:/START BATTLE/}).click();await page.waitForTimeout(3000);await page.locator('canvas').waitFor();await page.keyboard.down('KeyD');await page.waitForTimeout(300);await page.keyboard.up('KeyD');await page.mouse.move(800,400);await page.mouse.down();await page.waitForTimeout(250);await page.mouse.up();await page.keyboard.press('Space');await page.waitForTimeout(500);await page.getByRole('button',{name:'Pause'}).click();await page.getByText('PAUSED').waitFor();await page.getByRole('button',{name:/RESUME/}).click();await page.screenshot({path:'neon-desktop.png'});
const mobile=await browser.newPage({...devices['iPhone 13']});await wire(mobile);await mobile.goto(url,{waitUntil:'networkidle'});await mobile.getByRole('button',{name:/START SURVIVAL MATCH/}).click();await mobile.getByRole('button',{name:/PLAY THIS MAP/}).click();await mobile.getByRole('button',{name:/START BATTLE/}).click();await mobile.waitForTimeout(3000);if(!await mobile.locator('.mobile-joystick').isVisible())errors.push('mobile joystick hidden');if(!await mobile.locator('.attack-mobile').isVisible())errors.push('mobile attack hidden');if(!await mobile.locator('.dash-mobile').isVisible())errors.push('mobile dash hidden');await mobile.locator('.attack-mobile').tap();await mobile.locator('.dash-mobile').tap();await mobile.screenshot({path:'neon-mobile.png'});
await browser.close();console.log(JSON.stringify({ok:errors.length===0,errors,desktopMenus:true,gameplayInput:true,mobileControls:true},null,2));if(errors.length)process.exit(1);
